# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('move_count', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, b'Open'), (1, b'In Progress'), (2, b'Complete')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.BigIntegerField()),
                ('line_x_index', models.IntegerField()),
                ('line_y_index', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('won_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.PlayerModel')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='move_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.PlayerModel'),
        ),
        migrations.AddField(
            model_name='gamesquare',
            name='bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_line', to='game.LineSegment'),
        ),
        migrations.AddField(
            model_name='gamesquare',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='gamesquare',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_line', to='game.LineSegment'),
        ),
        migrations.AddField(
            model_name='gamesquare',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_line', to='game.LineSegment'),
        ),
        migrations.AddField(
            model_name='gamesquare',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_line', to='game.LineSegment'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='game.PlayerModel'),
        ),
    ]
