# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_count', models.BigIntegerField(default=0)),
                ('state_sequence', models.CharField(default=b'---------', max_length=9)),
                ('active_player_num', models.SmallIntegerField(choices=[(0, b'player1'), (1, b'player2')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='first_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='game.Player'),
        ),
    ]
