# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170505_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesquare',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='gamesquare',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamesquare',
            name='left',
        ),
        migrations.RemoveField(
            model_name='gamesquare',
            name='right',
        ),
        migrations.RemoveField(
            model_name='gamesquare',
            name='top',
        ),
        migrations.RemoveField(
            model_name='linesegment',
            name='game',
        ),
        migrations.RemoveField(
            model_name='square',
            name='game',
        ),
        migrations.RemoveField(
            model_name='square',
            name='won_by',
        ),
        migrations.RemoveField(
            model_name='tictactoemove',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tictactoemove',
            name='move_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='active_player_num',
            field=models.SmallIntegerField(choices=[(0, b'player1'), (1, b'player2')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='first_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='game.PlayerModel'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='game.PlayerModel'),
        ),
        migrations.AddField(
            model_name='game',
            name='state_sequence',
            field=models.CharField(default=b'---------', max_length=9),
        ),
        migrations.DeleteModel(
            name='GameSquare',
        ),
        migrations.DeleteModel(
            name='LineSegment',
        ),
        migrations.DeleteModel(
            name='Square',
        ),
        migrations.DeleteModel(
            name='TicTacToeMove',
        ),
    ]
