# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170507_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerModel',
            new_name='Player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_date',
        ),
    ]
